-- Generated by Stylix
local wezterm = require("wezterm")
wezterm.add_to_config_reload_watch_list(wezterm.config_dir)
-- Allow working with both the current release and the nightly
local config = {}
if wezterm.config_builder then
  config = wezterm.config_builder()
end
local stylix_base_config = {

    color_scheme = "stylix",
    window_frame = {
        active_titlebar_bg = "80766e",
        active_titlebar_fg = "4a4035",
        active_titlebar_border_bottom = "80766e",
        border_left_color = "e0e0e0",
        border_right_color = "e0e0e0",
        border_bottom_color = "e0e0e0",
        border_top_color = "e0e0e0",
        button_bg = "e0e0e0",
        button_fg = "4a4035",
        button_hover_bg = "4a4035",
        button_hover_fg = "80766e",
        inactive_titlebar_bg = "e0e0e0",
        inactive_titlebar_fg = "4a4035",
        inactive_titlebar_border_bottom = "80766e",
    },
    colors = {
      tab_bar = {
        background = "e0e0e0",
        inactive_tab_edge = "e0e0e0",
        active_tab = {
          bg_color = "ffffff",
          fg_color = "4a4035",
        },
        inactive_tab = {
          bg_color = "80766e",
          fg_color = "4a4035",
        },
        inactive_tab_hover = {
          bg_color = "4a4035",
          fg_color = "ffffff",
        },
        new_tab = {
          bg_color = "80766e",
          fg_color = "4a4035",
        },
        new_tab_hover = {
          bg_color = "4a4035",
          fg_color = "ffffff",
        },
      },
    },
    command_palette_bg_color = "e0e0e0",
    command_palette_fg_color = "4a4035",
    
    font = wezterm.font_with_fallback {
        "JetBrainsMono Nerd Font",
        "Noto Color Emoji",
    },
    font_size = 12,
    command_palette_font_size = 10,
    
    window_background_opacity = 1.000000,
}
for key, value in pairs(stylix_base_config) do
    config[key] = value
end
local function stylix_wrapped_config()
    return {
  window_padding = {
    left = 10,
    right = 10,
    top = 8,
    bottom = 8,
  },
}

end
local stylix_user_config = stylix_wrapped_config()
if stylix_user_config then
    for key, value in pairs(stylix_user_config) do
        config[key] = value
    end
end
return config

